### ISSUE TITLE
Unknown connector

### ISSUE THREAD

**Issue by wisxxx** [opencomputeproject/Time-Appliance-Project#18]
What is this external connector? It isn't in the schematic, but seems to be associated with the GNSS receiver.

![conn_unk](https://user-images.githubusercontent.com/52179570/129817324-7a86619c-5db3-483d-850a-b02d25d47723.png)

**Comment by ahmadexp** [comment]
That is a simple RF proto module which allows you to build all kinds of filters, attenuators, etc... 
At the moment I have a pass through (just a wire) inside it.
This was place there because we are planning to use an active antenna (GPS-OVER-FIBER) and that will require an attenuator (-30db) on the line to avoid receiver [input](<img width="468" alt="Screen Shot 2021-08-17 at 5 47 18 PM" src="https://user-images.githubusercontent.com/1751211/129818955-a8e55c33-5099-43f7-8f69-3a5bef4c7bce.png">) saturation.

**Comment by ahmadexp** [comment]
<img width="468" alt="Screen Shot 2021-08-17 at 5 47 18 PM" src="https://user-images.githubusercontent.com/1751211/129819088-c2cecf1d-2efa-4ddf-a845-8a34a6ff4d72.png">

**Comment by wisxxx** [comment]
Thanks. It seems then that I could use a simple SMA/SMA (or SMB/SMB) pass-through connector if I have a powered patch antenna a run of low-loss cable.

**Comment by ahmadexp** [comment]
That's right. I have done that too. 
<img width="1147" alt="Screen Shot 2021-08-17 at 5 59 20 PM" src="https://user-images.githubusercontent.com/1751211/129819887-d4992917-92e1-43f4-906f-265576da0e94.png">
